development:
   address: localhost
   port: 9312
   searhd_file_path: /home/banerjia/rails_app/graeters/db/sphinx
   stopwords: /home/banerjia/rails_app/graeters/db/sphinx/stopwords.txt
   exceptions: /home/banerjia/rails_app/graeters/db/sphinx/exceptions.txt
